sudo: required
dist: trusty
language: go
go:
  - 1.15.x
script:
  - |
    make container 
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
        make deploy
      fi
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
