ShortName: pxd
StorageClass:
  # Load a StorageClass from the given file. This file must be in the same directory as this one
  FromFile: /home2/grant/workspace/go/src/github.com/portworx/k8s-e2e-test/specs/storageclass.yaml
  
SnapshotClass:
  # Must be set to enable snapshotting tests
  FromFile: /home2/grant/workspace/go/src/github.com/portworx/k8s-e2e-test/specs/snapshotclass.yaml

DriverInfo:
  # Internal name of the driver, this is used as a display name in the test case and test objects
  Name: pxd

  # The range of disk size supported by this driver
  SupportedSizeRange:
    Min: 1Gi
    Max: 5Gi

  # Map of strings for supported FS types
  SupportedFsType:
    ext4: {}

  # Optional number of allowed topologies that the driver requires. Only relevenat if TopologyKeys is set
  NumAllowedTopologies: 0

  # Map of strings for required mount options
  # RequiredMountOption:

  # Optional list of access modes required for provisiong. Default is RWO
  RequiredAccessModes:
    - ReadWriteMany
    - ReadWriteOnce

  # Map that represents the capabilities the driver supports
  Capabilities:
    # Data is persistest accross pod restarts
    persistence: true

    # Volume ownership via fsGroup
    fsGroup: true

    # Raw block mode
    block: false

    # Exec a file in the volume
    exec: true

    # Support for volume limits
    volumeLimits: false

    # Support for volume exddpansion in controllers
    controllerExpansion: true

    # Support for volume expansion in nodes
    nodeExpansion: true

    # Support volume that an run on single node only (like hostpath)
    singleNodeVolume: false

    # Support ReadWriteMany access modes
    RWX: true

    # Support topology
    topology: false

    # Support populate data from snapshot
    snapshotDataSource: true

    # Support populated data from PVC
    pvcDataSource: true

InlineVolumes:
- Attributes: {}
