kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-sc
    annotations:
        storageclass.kubernetes.io/is-default-class: "true"
provisioner: pxd.portworx.com
allowVolumeExpansion: true
parameters:
    repl: "3"
    io_profile: "db"
